# Generated by Django 5.0.2 on 2024-02-09 02:41

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_email_student_first_name_student_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='First_Name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Last_Name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Username',
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default='uname', error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
            preserve_default=False,
        ),
    ]
